name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - release/*	  
  push:
    branches:
      - main
      - DIAN-237	  
      - DIAN-238	  
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Unit Test
        run: ./gradlew testReleaseUnitTest

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: UnitTestResults
          path: app/build/test-results # path to where the xml test results are stored
